---
# Title: sys-certbot-webroot
#
# Author: bitfinity-nl
# File: tasks/main.yml
# 
# Description:
#   Certbot is a free, open source software tool for automatically using 
#   Let’s Encrypt certificates on manually-administrated websites to enable HTTPS.
#
# Source(s):
#   - https://linuxize.com/post/secure-apache-with-let-s-encrypt-on-ubuntu-18-04/

- name: "Remove Certbot OS packages"
  apt:
    name:
    - certbot
    state: absent
          
- name: "Install snap packages"
  snap:
    name:
      - core

- name: "Install certbot packages"
  snap:
    name: certbot
    classic: yes

- name: "Symlink /snap/bin/certbot to /usr/bin/certbot"
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link   
    
# ----    
       
- name: "Generate strong DH (Diffie-Hellman) Group (4096 bits)"
  openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 4096
    
- name: "Create path for for validating request to /var/lib/letsencrypt/.well-known"
  file:
    path: /var/lib/letsencrypt/.well-known
    state: directory
    owner: www-data
    group: www-data
    mode: g+s

- name: "Transfer templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'apache2/letsencrypt.conf.j2', dest: '/etc/apache2/conf-available/letsencrypt.conf' }
    - { src: 'apache2/ssl-params.conf.j2', dest: '/etc/apache2/conf-available/ssl-params.conf' }
    - { src: 'default-ssl.conf.j2', dest: '/etc/apache2/sites-available/default-ssl.conf' }
  
- name: "Enable modules"
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
    - headers
    - http2

- name: "Enable configuration files"
  command: a2enconf letsencrypt ssl-params

- name: "Reload Apache2"
  systemd:
    name: apache2
    state: reloaded

- name: "Check if path /etc/letsencrypt/live/{{ le_domain }} exist"
  stat:
    path: "/etc/letsencrypt/live/{{ le_domain }}"
  register: result

- name: "Display if path /etc/letsencrypt/live/{{ le_domain }} exist"
  debug:
    msg: "{{ result.stat.exists }}"  
    
- name: "Retrieve Letsencrypt certificate for domain {{ le_domain }} with support e-mail {{ le_email }} if not exist"
  raw: "certbot certonly --agree-tos -n --email {{ le_email }} --webroot -w /var/lib/letsencrypt/ -d {{ le_domain }}"
  when: result.stat.exists == false
    
- name: "Renew Letsencrypt certificate for domain {{ le_domain }} with support e-mail {{ le_email }} if exists"
  raw: "sudo certbot renew"
  notify: reload_apache2
  when: result.stat.exists == true
  
- name: "Reload Apache2"
  systemd:
    name: apache2
    state: reloaded
